version: '3.2'

services:
  app:
    build: .
    image: app_img
    container_name: app_container
    volumes:
      - ./uwsgi.ini:/app/uwsgi.ini
    ports:
      - "5000:80"
    command: ["start_flask"]